---

dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
driver:
  name: openstack
platforms:
  - name: molecule-${ANSIBLE_ROLE_NAME} # TODO: Replace with Ansible role name.
    image: ${MOLECULE_OPENSTACK_IMAGE:-golden-image-${GOLDEN_IMAGE_VERSION}} # TODO: Replace with golden image version.
    flavor: ${MOLECULE_OPENSTACK_FLAVOR:-tiny}
    network: ${MOLECULE_OPENSTACK_NETWORK:-server_vlan}
    ssh_user: ${MOLECULE_OPENSTACK_SSH_USER:-${GOLDEN_IMAGE_SSH_USER}} # TODO: Replace with golden image default SSH user.
provisioner:
  name: ansible
verifier:
  name: testinfra
