---

- name: Prepare
  hosts: molecule-<< Ansible role >>
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      ansible.builtin.raw: test -e /usr/bin/python3 || yum install -y python3
      become: true
      changed_when: false
